# Generated by Django 5.0.7 on 2024-07-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover',
            new_name='capa',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='cover_in_post_content',
            new_name='capa_no_post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='conteudo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='excerpt',
            new_name='resumo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
    ]
