# Generated by Django 5.0.7 on 2024-07-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_cover_post_capa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preco_marketing',
            field=models.FloatField(default=0, verbose_name='preço'),
        ),
        migrations.AddField(
            model_name='post',
            name='preco_marketing_promocao',
            field=models.FloatField(default=0, verbose_name='preço promo'),
        ),
    ]
