# Generated by Django 5.0.7 on 2024-07-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='perfil',
            name='nome_completo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
