# Generated by Django 5.0.7 on 2024-08-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_perfil_data_nascimento_perfil_nome_completo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
