# Generated by Django 5.0.7 on 2024-08-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_myuserbase_delete_userbase_mb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuserbase',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='myuserbase',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
